server:
  host: "0.0.0.0"
  port: 8002
  endpoint: "/infer"

model:
  adapter: "openpi_rtc_triton"
  config_name: "pi05_ft_dosw1_qpos_foldclothes_merging_stage1"
  checkpoint: "/mlp_vepfs/share/myc/weight/openpi/pi05_ft_dosw1_qpos_foldclothes_merging_stage1_quant_baseline_49999_rtc2.pkl"
  prompt: "fold the cloth"
  adarms_knob: 0
  valid_action_num: 50
  action_horizon: 50
  action_type: "joint"
  image_size: [640, 480]
  tokenizer_path: "/mlp_vepfs/share/myc/weight/openpi/paligemma-3b-pt-224"
  norm_stats_dir: "/self_group/yc/ckpts/pi05_ft_dosw1_qpos_foldclothes_merging_stage1/quant_baseline/49999/assets/fold_cloth_sft_advantage"
  discrete_state_input: true
  state_dim: 14
  action_dim: 14
  noise_seed: null

inference:
  optimizer: "timeaxis_smooth"
  timeaxis_dt_ref_s: 0.016
  timeaxis_dt_min_s: 0.008
  timeaxis_dt_max_s: 0.025
  timeaxis_lambda_acc: 10.0
  timeaxis_lambda_time: 1.0
  timeaxis_stride: 50
  timeaxis_optdims: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  timeaxis_v_max: null
  timeaxis_lambda_v: 10.0
  timeaxis_horizon: 50
  timeaxis_logging: false
